### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [turettn/fastapi_offline#1]
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/fastapi-offline/1.0.0/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by turettn** [comment]
I did not realize wheels were useful for pure Python packages.  Thanks for the linked info.  I'll get that pushed tonight or tomorrow.

**Comment by turettn** [comment]
The wheel is up on PyPi now.  I'm planning on pushing a new version of the package once a month or so, just to keep rolling in the latest Swagger UI source files, and I'll make sure to do source & wheel distributions at the same time from now on.

**Comment by johnthagen** [comment]
Sounds great. Thanks!
