### ISSUE TITLE
redoc pages tries to pull fonts from the Internet

### ISSUE THREAD

**Issue by johnthagen** [turettn/fastapi_offline#14]
Not sure if there is much that can be done here, but the `/redoc` URL attempts to pull fonts from https://fonts.googleapis.com and https://fonts.gstatic.com even when `fastapi-offline` is used. Could these fonts be bundled in some way, or perhaps redoc could be configured to use local fonts instead?

I've seen similar configuration before in Material for Mkdocs, `font: false`: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#disabling-font-loading in case that is of any use.

**Comment by turettn** [comment]
Bundling the fonts got messy quickly.  They're licensed under an open-source license I never heard of, so there would be some checking before I would want to just start bundling them.

For bonus points, the redoc HTML page lives in `fastapi.openapi.docs`, and has the Google stylesheet URL hard-coded.  That appears to dynamically generate a CSS file, which then has further URLs pointing at the Google Fonts.  Bundling this would involve:
1. Patching FastAPI to make the Google Fonts URL configurable
2. Bundling the CSS
3. Parsing it to find the font URLs
4. Bundling those too

Luckily, FastAPI already had an option to disable Google fonts in favor of local fonts.  In the interest of simplicity & keeping the fastapi-offline package as small as possible, I went that route.

Favicon support (#13) should be pretty easy as well.  Once I have that done I'll cut `1.2.0` with both sets of changes.

**Comment by johnthagen** [comment]
> Luckily, FastAPI already had an option to disable Google fonts in favor of local fonts.

This sounds great, and I agree a much better solution. 👍 

Thanks!
