### ISSUE TITLE
Configurable doc paths

### ISSUE THREAD

**Issue by robinderat** [turettn/fastapi_offline#17]
It's only a slight inconvenience, but could you make it so the docs and redoc urls are configurable, rather than being hardcoded? Perhaps the docs_url and redoc_url could even be used for this, making usage even more similar to FastAPI

**Comment by turettn** [comment]
@robinderat  I didn't think about this option initially - thanks for the feedback!  I made the changes as you suggested.

This should work now:

```python
app = FastAPIOffline(docs_url='/asdf', redoc_url='/qwerty')
```

Setting either option to `None` disables that part of the documentation.

This is up on PyPi as version 1.3.0.

**Comment by turettn** [comment]
@johnthagen You had asked for the ability to disable docs in #2.  At the time, we ignored the case where someone would want to disable one but not the other.  Once the ability to change the paths was added, the ability to disable them individually came basically for free.

fastapi-offline will still complain bitterly if you manually set `openapi_url` to `None`, but I'm still thinking that's a case where fastapi-offline does you absolutely no good and you should just use normal fastapi.
