### ISSUE TITLE
Missing py.typed on fastapi_offline

### ISSUE THREAD

**Issue by staticdev** [turettn/fastapi_offline#21]
mypy complains about that:

```
error: Skipping analyzing "fastapi_offline": module is installed, but missing library stubs of py.typed marker [import]
```

**Comment by staticdev** [comment]
Thanks for merging @turettn! Do you mind releasing a patch version?

**Comment by turettn** [comment]
Not at all - I'll get that done sometime today.

**Comment by turettn** [comment]
Done!  It's up on PyPi as v1.3.2.

Thanks again for the PR - I didn't know that the marker file was required.

**Comment by staticdev** [comment]
Tested, works like charm.
