### ISSUE TITLE
 update Swagger UI  v5.3.2 

### ISSUE THREAD

**Issue by honglei** [turettn/fastapi_offline#37]
Pls update Swagger UI to [[Swagger UI v5.3.2 Released!](https://github.com/swagger-api/swagger-ui/releases/tag/v5.3.2) [L](https://github.com/swagger-api/swagger-ui/releases/latest)]

**Comment by turettn** [comment]
:wave: This one slipped by me.  I'll get a new version up in the next day or two.

**Comment by turettn** [comment]
v1.6.1 includes the newest version of swagger & should be available on PyPi.
